### ISSUE TITLE
系统界面已停止运行

### ISSUE THREAD

**Issue by yrccondor** [Nevolution/sdk#17]
任何时候只要打开过 Nevolution，之后每次试图进入最近任务界面时都会提示“系统界面已停止运行”，然后系统回到锁屏界面，此时系统其他功能正常，Nevolution 也正常运行。重启后一切正常，且 Nevolution 进程也正常运行，但点击 Nevolution icon 打开设置后会再次出现上面的情况，除非重启，否则无法恢复正常。

使用 Nevolution 3.0.2，LOS 15.1(8.1)，Mi 5。

部分错误日志：
```
--------- beginning of crash
01-13 15:11:59.334  1631  1631 E AndroidRuntime: FATAL EXCEPTION: main
01-13 15:11:59.334  1631  1631 E AndroidRuntime: Process: com.android.systemui, PID: 1631
01-13 15:11:59.334  1631  1631 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.server.wm.TaskWindowContainerController.getBounds(android.graphics.Rect)' on a null object reference
01-13 15:11:59.334  1631  1631 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2019)
01-13 15:11:59.334  1631  1631 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1959)
01-13 15:11:59.334  1631  1631 E AndroidRuntime: 	at android.app.IActivityManager$Stub$Proxy.getAllStackInfos(IActivityManager.java:7773)
01-13 15:11:59.334  1631  1631 E AndroidRuntime: 	at com.android.systemui.recents.misc.SystemServicesProxy.isRecentsActivityVisible(SystemServicesProxy.java:520)
01-13 15:11:59.334  1631  1631 E AndroidRuntime: 	at com.android.systemui.recents.RecentsImpl.lambda$-com_android_systemui_recents_RecentsImpl_22230(RecentsImpl.java:477)
01-13 15:11:59.334  1631  1631 E AndroidRuntime: 	at com.android.systemui.recents.-$Lambda$pgmD0Bxm8kFYR7cdcGYk6DUhgds.$m$0(Unknown Source:8)
01-13 15:11:59.334  1631  1631 E AndroidRuntime: 	at com.android.systemui.recents.-$Lambda$pgmD0Bxm8kFYR7cdcGYk6DUhgds.run(Unknown Source:0)
01-13 15:11:59.334  1631  1631 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:790)
01-13 15:11:59.334  1631  1631 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-13 15:11:59.334  1631  1631 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
01-13 15:11:59.334  1631  1631 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
01-13 15:11:59.334  1631  1631 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-13 15:11:59.334  1631  1631 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
01-13 15:11:59.334  1631  1631 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
...
01-13 15:12:44.746  2730  2958 E CrashlyticsCore: Error occurred sending report bq@87ba7c1
01-13 15:12:44.746  2730  2958 E CrashlyticsCore: aie$c: java.io.FileNotFoundException: /data/user/0/com.oasisfeng.nevo/files/.Fabric/com.crashlytics.sdk.android.crashlytics-core/invalidClsFiles/5C3AE3AF00CA-0001-09A6-D32A1AF1313CSessionEvent0000000000.cls_temp (No such file or directory)
01-13 15:12:44.746  2730  2958 E CrashlyticsCore: 	at aie.a(SourceFile:2619)
01-13 15:12:44.746  2730  2958 E CrashlyticsCore: 	at bm.a(SourceFile:102)
01-13 15:12:44.746  2730  2958 E CrashlyticsCore: 	at bm.a(SourceFile:61)
01-13 15:12:44.746  2730  2958 E CrashlyticsCore: 	at ay.a(SourceFile:18)
01-13 15:12:44.746  2730  2958 E CrashlyticsCore: 	at cg.a(SourceFile:104)
01-13 15:12:44.746  2730  2958 E CrashlyticsCore: 	at cg$e.b(SourceFile:242)
01-13 15:12:44.746  2730  2958 E CrashlyticsCore: 	at cg$e.a(SourceFile:185)
01-13 15:12:44.746  2730  2958 E CrashlyticsCore: 	at agm.run(SourceFile:30)
01-13 15:12:44.746  2730  2958 E CrashlyticsCore: 	at java.lang.Thread.run(Thread.java:764)
01-13 15:12:44.746  2730  2958 E CrashlyticsCore: Caused by: java.io.FileNotFoundException: /data/user/0/com.oasisfeng.nevo/files/.Fabric/com.crashlytics.sdk.android.crashlytics-core/invalidClsFiles/5C3AE3AF00CA-0001-09A6-D32A1AF1313CSessionEvent0000000000.cls_temp (No such file or directory)
01-13 15:12:44.746  2730  2958 E CrashlyticsCore: 	at java.io.FileInputStream.open0(Native Method)
01-13 15:12:44.746  2730  2958 E CrashlyticsCore: 	at java.io.FileInputStream.open(FileInputStream.java:200)
01-13 15:12:44.746  2730  2958 E CrashlyticsCore: 	at java.io.FileInputStream.<init>(FileInputStream.java:150)
01-13 15:12:44.746  2730  2958 E CrashlyticsCore: 	at aie.a(SourceFile:2616)
01-13 15:12:44.746  2730  2958 E CrashlyticsCore: 	... 8 more
```
日志较长，不确定是否找到了关键日志，见谅

**Comment by oasisfeng** [comment]
Fixed in v3.0.4.
